/*

    1. I don't understand what to write next !
        -whether it is pointer -> or .

    2. I don't know which is a function , which is a member, they all look similar
        Eg : Getter examples generated by VS Code

            std::string id()const{
                return _id;
            }

            Magic(std::Vector<Vehicle*>& data, int id);

    3. Comprehension Skills [ Problem statement not read carefully ]

*/
